#%RAML 0.8
---
title: BiH elections API
baseUri: http://api.tbd.zastone.ba/{version}
version: v1

/municipalities:
  get:
    description: Retrieves (optionally filtered) municipality meta-data
    responses:
      200:
        body:
          application/json:
            example: |
              "municipalities":
              [
                {
                  "id": 1,
                  "name": "Velika Kladusa",
                  "kanton": 201,
                  "parliament_bih": 341,
                  "parliament_fbih": 451,
                  "parliament_rs": 123,
                  "president_bih": 234,
                  "president_rs": 345
                }
              ]
/candidates:
/seats:
/results:
