#%RAML 0.8
---
title: BiH elections API
baseUri: http://api.tbd.zastone.ba/{version}
version: v1

resourceTypes:
  - results:
      uriParameters:
        election_type:
          description: "Election type"
          enum:
            - kanton
            - parliament_bih
            - parliament_fbih
            - parliament_rs
            - president_bih
            - president_rs
        year:
          description: "Valid election type"
          type: integer

/municipalities:
  get:
    description: Retrieves (optionally filtered) municipality meta-data
    responses:
      200:
        body:
          application/json:
            example: |
              "municipalities":
              [
                {
                  "id": 1,
                  "name": "Velika Kladusa",
                  "kanton": 201,
                  "parliament_bih": 341,
                  "parliament_fbih": 451,
                  "parliament_rs": 123,
                  "president_bih": 234,
                  "president_rs": 345
                }
              ]
/results/{election_type}/{year}:
  type: results
  get:
    queryParameters:
      # None
    responses:
      200:
        description: "Election results for given election type and year"
        body:
          application/json:
            example: |
              "request": {
                "election_type": "parl_bih",
                "year": 2010
              },
              "results_per_municipality": [
                {
                  "name": "Foo",
                  "id": "123",
                  "electoral_unit_id": "511",
                  "results": [{
                    "name": "Bar",
                    "votes": 5
                  }]
                }
              ]
      404:
        description: "Missing election data"
/mandates/{election_type}/{year}:
  type: results
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              "request": {
                "election_type": "parl_bih",
                "year": 2010
              },
              "results_per_electoral_unit": [
                {
                  "electoral_unit_name": "Foo", /* Optional */
                  "electoral_unit_id": "511",
                  "mandates": [
                    {
                      "name": "Bar",
                      "seats": 8
                    },
                    { 
                      "name": "Tie between: Foo & Bar",
                      "seats": 1
                    }
                  ]
                },
                {
                  "electoral_unit_name": "Compensatory",
                  "electoral_unit_id": "599",
                  "mandates": [
                    {
                      "name": "Bar",
                      "seats": 10
                    }
                  ]
                }
              ]
